server:
  port: 8700
  context-path: /
logging:
  level:
    com.wade.dingtalk: debug
    root: info
jwt:
  header: Authorization
  secret: hvLVNnEQwOvW15DqXqcLPACGt2W+O8QkJbFpIiRyBLHj63BXMiIVHJqpoB4L3gUw5xPOx3MgmmiQ6n8GvRhGGA==
  expiration: 604800
  tokenHead: "Bearer "
#  route:
#    authentication:
#      path: auth
#      refresh: refresh
#      register: "auth/register"